<?php 
namespace BlueFission\Automata\Language;

class Interpreter {

	// private $_tokenizer;
	private $_grammar;
	private $_documenter;
	private $_walker;

	public function __construct() {
		// $this->_tokenizer = new Tokenizer();
		$this->_grammar = new Grammar();
		$this->_documenter = new Documenter();
		$this->_walker = new Walker();
	}

	// Load Source
	public function load( $sourceFile ) {
		$contents = file_get_contents( $sourceFile );
		$this->run($contents);
	}

	// Load Grammer Rules
	public function grammar() {

		$rules = array();

		foreach ( $rules as $a=>$b ) {
			$grammar->addRule($a, $b);
		}
	}

	// Inject Grammer into Tokenizer Parser
	// Read source code in Tokenizer Parser
	public function run( $code ) {
		$tokens = Tokenizer::parse($code, $this->_grammar);

		// Read and run Tokenized data in Documenter
		foreach ( $tokens as $token ) {
			$this->_documenter->push($token);
		}

		// Create a scenario tree
		$tree = $this->_documenter->getTree();

		// Traverse Statements with Walker
		// Push Statement into Walker	
		$this->_walker->traverse($tree);
		
		// Prompt statements generated by Composer
		$this->_walker->process();
	}
}